#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

GITCONFIG="${HOME}/.gitconfig"
INCLUDE_DIRECTIVE='path="~/.git-include"'

if ! grep --quiet "${INCLUDE_DIRECTIVE}" "${GITCONFIG}" 2> /dev/null; then
  cat << EOF >> "${GITCONFIG}"

[include]
  ${INCLUDE_DIRECTIVE}
EOF
fi


SSHCONFIG="${HOME}/.ssh/config"
INCLUDE_DIRECTIVE='Include config.d/github'

if ! grep --quiet "${INCLUDE_DIRECTIVE}" "${SSHCONFIG}" 2> /dev/null; then
  cat << EOF >> "${SSHCONFIG}"
${INCLUDE_DIRECTIVE}
EOF
fi
